name: "Test"
on:
  pull_request:
  push:
jobs:
  build-and-push:
    strategy:
      matrix:
        include:
          - python-version: python:3.11-gdal
            nix-attr: python311-gdal
          - python-version: python:3.10-gdal
            nix-attr: python310-gdal
          - python-version: python:3.11
            nix-attr: python311
          - python-version: python:3.10
            nix-attr: python310
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Log into ghcr
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: 'ghcr.io'
        username: '${{ github.actor }}'
        password: '${{ secrets.GITHUB_TOKEN }}'
    - run: 'nix build .#${{matrix.nix-attr}}'
    - run: scripts/push_image.sh
      env:
        IMAGE_URI: 'docker://ghcr.io/loftylabs/python-nix-images/${{ matrix.python-version }}'
        NIX_PACKAGE: '${{matrix.nix-attr}}'
