name: "Test"
on:
  pull-request:
    branches:
      - main
    types:
      - closed
    #   have pinned dependencies, not necessary unless we want to auto upgrade nixpkgs references
    #
    #   schedule:
    #     # https://crontab.guru/#30_0_*_*_*
    #     # Every day at 00:30
    #     - cron: '30 0 * * *'
jobs:
  build-and-push:
    strategy:
      matrix:
        include:
          - python-version: python:3.11-gdal
            nix-attr: python311-gdal
          - python-version: python:3.10-gdal
            nix-attr: python310-gdal
          - python-version: python:3.11
            nix-attr: python311
          - python-version: python:3.10
            nix-attr: python310
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Log into ghcr
      uses: docker/login-action@v2
      with:
        registry: 'ghcr.io'
        username: '${{ github.actor }}'
        password: '${{ secrets.GITHUB_TOKEN }}'
    - run: 'nix build .#${{matrix.nix-attr}}'
    - run: scripts/push_image.sh
      env:
        IMAGE_URI: 'docker://ghcr.io/loftylabs/python-nix-images/${{ matrix.python-version }}'
        NIX_PACKAGE: '${{matrix.nix-attr}}'
  scan-images:
    needs: build-and-push
    strategy:
      matrix:
        include:
          - python-version: python:3.11-gdal
            nix-attr: python311-gdal
          - python-version: python:3.10-gdal
            nix-attr: python310-gdal
          - python-version: python:3.11
            nix-attr: python311
          - python-version: python:3.10
            nix-attr: python310
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/loftylabs/python-nix-images/${{ matrix.python-version }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

