name: "Diff new closures"
on:
  pull_request:
jobs:
  produce-diff-via-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1
      - run: scripts/diff-attrs.py
        id: closure-diff
        env:
          HEAD_REF: ${{github.event.pull_request.head.sha}}
          BASE_REF: ${{github.event.pull_request.base.sha}}
      - name: Comment PR with Closure
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: closure-diff 
          filePath: ./log.txt
